# Generated by Django 5.0.6 on 2024-06-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="alt",
            field=models.CharField(blank=True, default="No image", max_length=200),
        ),
    ]
