# Generated by Django 5.0.6 on 2024-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0006_alter_productimage_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="alt",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
