# Generated by Django 5.0.6 on 2024-06-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0009_category_alt_category_src_delete_categoryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
