# Generated by Django 5.0.6 on 2024-06-07 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0010_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="shopapp.product",
            ),
        ),
    ]
