# Generated by Django 5.0.6 on 2024-06-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0013_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
    ]
