# Generated by Django 5.0.6 on 2024-06-14 11:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0002_alter_profile_email_alter_profile_phone"),
        ("shopapp", "0014_alter_tag_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="shopapp.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="myauth.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="rate",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="text",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
