# Generated by Django 5.0.6 on 2024-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0016_alter_review_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="profile",
        ),
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.CharField(default="some code", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="email",
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
