# Generated by Django 5.0.6 on 2024-06-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0018_specification"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="limited_edition",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sort_index",
            field=models.IntegerField(default=0),
        ),
    ]
