# Generated by Django 5.0.6 on 2024-06-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0020_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
