# Generated by Django 5.0.6 on 2024-06-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0002_alter_profile_email_alter_profile_phone"),
        ("shopapp", "0021_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="myauth.profile",
            ),
        ),
    ]
