# Generated by Django 5.0.6 on 2024-06-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0022_alter_order_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="totalCost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
