# Generated by Django 5.0.6 on 2024-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0024_orderdeliverytype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdeliverytype",
            name="delivery_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="orderdeliverytype",
            name="min_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
