# Generated by Django 5.0.6 on 2024-06-18 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0026_alter_orderdeliverytype_delivery_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=4)),
                ("month", models.CharField(max_length=2)),
                ("code", models.CharField(max_length=4)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="shopapp.order",
                    ),
                ),
            ],
        ),
    ]
