# Generated by Django 5.0.6 on 2024-06-19 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0027_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="number",
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salePrice",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("dateFrom", models.DateField()),
                ("dateTo", models.DateField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="shopapp.product",
                    ),
                ),
            ],
        ),
    ]
